/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf --transform
Author: misterdevious (https://sketchfab.com/misterdevious)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/frank-0eb1f1757349489eab05a0f03cff5b46
Title: Frank
*/

import React, { useRef, ComponentProps } from 'react'
import { useGLTF } from '@react-three/drei'
import { Mesh, Material } from 'three'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    FranksC352SC130kDC32270kM2064k_0: Mesh
  },
  materials: {
    'Franks.C352.SC130k.DC32270k.M2064k': Material
  }
}

export function Statue(props: ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('./models/statue/scene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.FranksC352SC130kDC32270kM2064k_0.geometry} material={materials['Franks.C352.SC130k.DC32270k.M2064k']} rotation={[2.016, -0.624, -0.704]} scale={0.063} />
    </group>
  )
}

useGLTF.preload('./models/statue/scene-transformed.glb')
